-- Teepsaa — Split users table into buyers, vendors, admins
-- Run once on existing database. Safe to re-run if interrupted (tables are created with IF NOT EXISTS).

SET foreign_key_checks = 0;

-- ── Step 1: Create new tables ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS buyers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vendors (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    aba_qr VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admins (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── Step 2: Migrate existing data (IDs preserved so FKs stay valid) ───────

INSERT IGNORE INTO buyers (id, email, password, created_at)
    SELECT id, email, password, created_at FROM users WHERE role = 'buyer';

INSERT IGNORE INTO vendors (id, email, password, aba_qr, created_at)
    SELECT id, email, password, aba_qr, created_at FROM users WHERE role = 'vendor';

INSERT IGNORE INTO admins (id, email, password, created_at)
    SELECT id, email, password, created_at FROM users WHERE role = 'admin';

-- ── Step 3: Drop old FKs from dependent tables (names auto-generated by MySQL) ──

-- businesses.user_id → was users(id), now vendors(id)
SET @fk = (SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE
           WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'businesses'
           AND REFERENCED_TABLE_NAME = 'users' LIMIT 1);
SET @sql = IF(@fk IS NOT NULL, CONCAT('ALTER TABLE businesses DROP FOREIGN KEY `', @fk, '`'), 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- cart_items.buyer_user_id → was users(id), now buyers(id)
SET @fk = (SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE
           WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cart_items'
           AND REFERENCED_TABLE_NAME = 'users' AND COLUMN_NAME = 'buyer_user_id' LIMIT 1);
SET @sql = IF(@fk IS NOT NULL, CONCAT('ALTER TABLE cart_items DROP FOREIGN KEY `', @fk, '`'), 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- payments.buyer_user_id → was users(id), now buyers(id)
SET @fk = (SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE
           WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'payments'
           AND REFERENCED_TABLE_NAME = 'users' LIMIT 1);
SET @sql = IF(@fk IS NOT NULL, CONCAT('ALTER TABLE payments DROP FOREIGN KEY `', @fk, '`'), 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- orders.buyer_user_id → was users(id), now buyers(id)
SET @fk = (SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE
           WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'orders'
           AND REFERENCED_TABLE_NAME = 'users' AND COLUMN_NAME = 'buyer_user_id' LIMIT 1);
SET @sql = IF(@fk IS NOT NULL, CONCAT('ALTER TABLE orders DROP FOREIGN KEY `', @fk, '`'), 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- ── Step 4: Add correct FKs pointing to new tables ────────────────────────

ALTER TABLE businesses
    ADD CONSTRAINT fk_businesses_vendor FOREIGN KEY (user_id) REFERENCES vendors(id) ON DELETE CASCADE;

ALTER TABLE cart_items
    ADD CONSTRAINT fk_cart_buyer FOREIGN KEY (buyer_user_id) REFERENCES buyers(id) ON DELETE CASCADE;

ALTER TABLE payments
    ADD CONSTRAINT fk_payments_buyer FOREIGN KEY (buyer_user_id) REFERENCES buyers(id) ON DELETE CASCADE;

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_user_id) REFERENCES buyers(id) ON DELETE CASCADE;

-- ── Step 5: Drop old users table ──────────────────────────────────────────

DROP TABLE IF EXISTS users;

SET foreign_key_checks = 1;
