<?php
// Default email templates — the source of truth for seeding `email_templates`
// and the safe fallback used by render_email_template() if a DB row is missing.
// Bodies are raw HTML. {tokens} are replaced with real values at send time;
// staff may reword around them but must keep the tokens intact.
//
// Available tokens per template are listed in `tokens`. Special tokens:
//   {code}  — the styled verification-code block (verify_code)
//   {link}  — the reset link (reset_password)
//   {summary} — the order item table + total (order_received)
//   {cart_list} — the cart <ul> of items (abandoned_cart)

return [
    'order_received' => [
        'label'   => 'Order received (buyer)',
        'tokens'  => '{summary}',
        'subject_km' => 'បានទទួលការបញ្ជាទិញ — ទីផ្សារ',
        'subject_en' => 'Order received — teepsaa',
        'heading_km' => 'យើងបានទទួលការបញ្ជាទិញរបស់អ្នក!',
        'heading_en' => 'We received your order!',
        'body_km' => '{summary}<p style="margin:16px 0 0;font-size:0.85rem;color:#666">យើងនឹងផ្ទៀងផ្ទាត់ការបង់ប្រាក់ ABA របស់អ្នក ហើយបញ្ជាក់ការបញ្ជាទិញក្នុងរយៈពេល ១ ម៉ោង។ អ្នកនឹងទទួលអ៊ីមែលមួយទៀតនៅពេលបញ្ជាក់រួច។</p>',
        'body_en' => 'We\'ll verify your ABA payment and confirm your order within 1 hour. You\'ll receive another email once confirmed.',
        'cta_km' => 'មើលការបញ្ជាទិញរបស់ខ្ញុំ',
        'cta_en' => 'View my orders',
    ],
    'payment_confirmed' => [
        'label'   => 'Payment confirmed (buyer)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការបង់ប្រាក់របស់អ្នកត្រូវបានបញ្ជាក់',
        'subject_en' => 'Your payment has been confirmed',
        'heading_km' => 'ការបង់ប្រាក់ត្រូវបានបញ្ជាក់',
        'heading_en' => 'Payment confirmed',
        'body_km' => 'ជម្រាបសួរ {name}, ការបង់ប្រាក់សម្រាប់ការបញ្ជាទិញ <strong>#{order}</strong> ត្រូវបានបញ្ជាក់។ អ្នកលក់កំពុងរៀបចំការបញ្ជាទិញរបស់អ្នក។',
        'body_en' => 'Hi {name}, your payment for order <strong>#{order}</strong> has been confirmed. The vendor is now preparing your order.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'order_dispatched' => [
        'label'   => 'Order dispatched (buyer)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការបញ្ជាទិញរបស់អ្នកកំពុងធ្វើដំណើរ',
        'subject_en' => 'Your order is on its way',
        'heading_km' => 'ការបញ្ជាទិញត្រូវបានបញ្ជូន',
        'heading_en' => 'Order dispatched',
        'body_km' => 'ជម្រាបសួរ {name}, ការបញ្ជាទិញ <strong>#{order}</strong> របស់អ្នកត្រូវបានបញ្ជូន។ អ្នកអាចបញ្ជាក់ការទទួលនៅពេលវាមកដល់។',
        'body_en' => 'Hi {name}, your order <strong>#{order}</strong> has been dispatched. You can confirm delivery once it arrives.',
        'cta_km' => 'តាមដានការបញ្ជាទិញ',
        'cta_en' => 'Track order',
    ],
    'payout_sent' => [
        'label'   => 'Payout sent (vendor)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការទូទាត់ត្រូវបានផ្ញើ',
        'subject_en' => 'Your payout has been sent',
        'heading_km' => 'ការទូទាត់ត្រូវបានផ្ញើ',
        'heading_en' => 'Payout sent',
        'body_km' => 'ជម្រាបសួរ {name}, ការទូទាត់សម្រាប់ការបញ្ជាទិញ <strong>#{order}</strong> ត្រូវបានផ្ញើទៅគណនី ABA របស់អ្នក។',
        'body_en' => 'Hi {name}, your payout for order <strong>#{order}</strong> has been sent to your ABA account.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'delivery_confirmed' => [
        'label'   => 'Delivery confirmed (vendor)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការដឹកជញ្ជូនត្រូវបានបញ្ជាក់ — ការទូទាត់នឹងមកដល់',
        'subject_en' => 'Delivery confirmed — payout incoming',
        'heading_km' => 'ការដឹកជញ្ជូនត្រូវបានបញ្ជាក់',
        'heading_en' => 'Delivery confirmed',
        'body_km' => 'ជម្រាបសួរ {name}, អ្នកទិញបានបញ្ជាក់ការទទួលការបញ្ជាទិញ <strong>#{order}</strong>។ ទីផ្សារនឹងដំណើរការការទូទាត់របស់អ្នកក្នុងពេលឆាប់ៗ។',
        'body_en' => 'Hi {name}, the buyer has confirmed receipt of order <strong>#{order}</strong>. Teepsaa will process your payout shortly.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'low_stock' => [
        'label'   => 'Low stock alert (vendor)',
        'tokens'  => '{name}, {product}, {units}',
        'subject_km' => 'ការជូនដំណឹងស្តុកជិតអស់ — {product}',
        'subject_en' => 'Low stock alert — {product}',
        'heading_km' => 'ការជូនដំណឹងស្តុកជិតអស់',
        'heading_en' => 'Low stock alert',
        'body_km' => 'ជម្រាបសួរ {name}, <strong>{product}</strong> នៅសល់តែ <strong>{units} គ្រឿង</strong> ប៉ុណ្ណោះ។ សូមបំពេញស្តុកឆាប់ៗ ដើម្បីបន្តលក់។',
        'body_en' => 'Hi {name}, <strong>{product}</strong> has only <strong>{units} remaining</strong>. Restock soon to keep selling.',
        'cta_km' => 'ធ្វើបច្ចុប្បន្នភាពស្តុក',
        'cta_en' => 'Update stock',
    ],
    'abandoned_cart' => [
        'label'   => 'Abandoned cart (buyer)',
        'tokens'  => '{name}, {cart_list}',
        'subject_km' => 'រទេះ ទីផ្សារ របស់អ្នកកំពុងរង់ចាំ',
        'subject_en' => 'Your teepsaa cart is waiting',
        'heading_km' => 'អ្នកបានទុកអ្វីមួយក្នុងរទេះ',
        'heading_en' => 'You left something in your cart',
        'body_km' => 'ជម្រាបសួរ {name}, អ្នកមានទំនិញកំពុងរង់ចាំក្នុងរទេះ ទីផ្សារ របស់អ្នក៖{cart_list}រទេះរបស់អ្នកត្រូវបានរក្សាទុក — ត្រឡប់មកវិញនៅពេលអ្នកត្រៀមរួច។',
        'body_en' => 'Hi {name}, you have items waiting in your teepsaa cart. Your cart is saved — head back whenever you\'re ready.',
        'cta_km' => 'ទៅរទេះរបស់ខ្ញុំ',
        'cta_en' => 'Go to my cart',
    ],
    'review_reminder' => [
        'label'   => 'Review reminder (buyer)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'តើការបញ្ជាទិញ ទីផ្សារ របស់អ្នកដូចម្តេច?',
        'subject_en' => 'How was your teepsaa order?',
        'heading_km' => 'តើការបញ្ជាទិញរបស់អ្នកដូចម្តេចដែរ?',
        'heading_en' => 'How was your order?',
        'body_km' => 'ជម្រាបសួរ {name}, ការបញ្ជាទិញ ទីផ្សារ <strong>{order}</strong> របស់អ្នកត្រូវបានដឹកជញ្ជូន។ យើងចង់ដឹងពីគំនិតរបស់អ្នក — វាចំណាយពេលតែបន្តិចប៉ុណ្ណោះ។',
        'body_en' => 'Hi {name}, your teepsaa order <strong>{order}</strong> was delivered. We\'d love to hear what you think — it only takes a moment.',
        'cta_km' => 'ទុកមតិយោបល់',
        'cta_en' => 'Leave a review',
    ],
    'verify_code' => [
        'label'   => 'Email verification code',
        'tokens'  => '{name}, {code}',
        'subject_km' => 'កូដផ្ទៀងផ្ទាត់ ទីផ្សារ របស់អ្នក',
        'subject_en' => 'Your Teepsaa verification code',
        'heading_km' => 'ផ្ទៀងផ្ទាត់អ៊ីមែលរបស់អ្នក',
        'heading_en' => 'Verify your email',
        'body_km' => 'ជម្រាបសួរ {name}, កូដផ្ទៀងផ្ទាត់របស់អ្នកគឺ៖{code}កូដនេះនឹងផុតកំណត់ក្នុងរយៈពេល ១៥ នាទី។ ប្រសិនបើអ្នកមិនបានបង្កើតគណនី ទីផ្សារ សូមមិនអើពើនឹងអ៊ីមែលនេះ។',
        'body_en' => 'Hi {name}, your verification code is shown above. It expires in 15 minutes. If you didn\'t create a Teepsaa account, ignore this email.',
        'cta_km' => null,
        'cta_en' => null,
    ],
    'reset_password' => [
        'label'   => 'Password reset',
        'tokens'  => '{name}, {link}',
        'subject_km' => 'កំណត់ពាក្យសម្ងាត់ ទីផ្សារ របស់អ្នកឡើងវិញ',
        'subject_en' => 'Reset your Teepsaa password',
        'heading_km' => 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
        'heading_en' => 'Reset your password',
        'body_km' => 'ជម្រាបសួរ {name}, សូមចុចលើតំណខាងក្រោមដើម្បីកំណត់ពាក្យសម្ងាត់របស់អ្នកឡើងវិញ។ តំណនេះមានសុពលភាពរយៈពេល ១ ម៉ោង។{link}ប្រសិនបើអ្នកមិនបានស្នើសុំកំណត់ពាក្យសម្ងាត់ឡើងវិញ សូមមិនអើពើនឹងអ៊ីមែលនេះ។',
        'body_en' => 'Hi {name}, click the link above to reset your password. This link is valid for 1 hour. If you didn\'t request a password reset, you can ignore this email.',
        'cta_km' => null,
        'cta_en' => null,
    ],
];
