<?php
// Default email templates — the source of truth for seeding `email_templates`
// and the safe fallback used by render_email_template() if a DB row is missing.
// Bodies are raw HTML. {tokens} are replaced with real values at send time;
// staff may reword around them but must keep the tokens intact.
//
// Available tokens per template are listed in `tokens`. Special tokens:
//   {code}  — the styled verification-code block (verify_code)
//   {link}  — the reset link (reset_password)
//   {summary} — the order item table + total (order_received)
//   {cart_list} — the cart <ul> of items (abandoned_cart)

return [
    'order_received' => [
        'label'   => 'Order received (buyer)',
        'tokens'  => '{summary}',
        'subject_km' => 'បានទទួលការបញ្ជាទិញ — ទីផ្សារ',
        'subject_en' => 'Order received — teepsaa',
        'heading_km' => 'យើងបានទទួលការបញ្ជាទិញរបស់អ្នក!',
        'heading_en' => 'We received your order!',
        'body_km' => '{summary}<p style="margin:16px 0 0;font-size:0.85rem;color:#666">យើងនឹងផ្ទៀងផ្ទាត់ការបង់ប្រាក់ ABA របស់អ្នក ហើយបញ្ជាក់ការបញ្ជាទិញក្នុងរយៈពេល ១ ម៉ោង។ អ្នកនឹងទទួលអ៊ីមែលមួយទៀតនៅពេលបញ្ជាក់រួច។</p>',
        'body_en' => 'We\'ll verify your ABA payment and confirm your order within 1 hour. You\'ll receive another email once confirmed.',
        'cta_km' => 'មើលការបញ្ជាទិញរបស់ខ្ញុំ',
        'cta_en' => 'View my orders',
    ],
    'payment_confirmed' => [
        'label'   => 'Payment confirmed (buyer)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការបង់ប្រាក់របស់អ្នកត្រូវបានបញ្ជាក់',
        'subject_en' => 'Your payment has been confirmed',
        'heading_km' => 'ការបង់ប្រាក់ត្រូវបានបញ្ជាក់',
        'heading_en' => 'Payment confirmed',
        'body_km' => 'ជម្រាបសួរ {name}, ការបង់ប្រាក់សម្រាប់ការបញ្ជាទិញ <strong>#{order}</strong> ត្រូវបានបញ្ជាក់។ អ្នកលក់កំពុងរៀបចំការបញ្ជាទិញរបស់អ្នក។',
        'body_en' => 'Hi {name}, your payment for order <strong>#{order}</strong> has been confirmed. The vendor is now preparing your order.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'order_dispatched' => [
        'label'   => 'Order dispatched (buyer)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការបញ្ជាទិញរបស់អ្នកកំពុងធ្វើដំណើរ',
        'subject_en' => 'Your order is on its way',
        'heading_km' => 'ការបញ្ជាទិញត្រូវបានបញ្ជូន',
        'heading_en' => 'Order dispatched',
        'body_km' => 'ជម្រាបសួរ {name}, ការបញ្ជាទិញ <strong>#{order}</strong> របស់អ្នកត្រូវបានបញ្ជូន។ អ្នកអាចបញ្ជាក់ការទទួលនៅពេលវាមកដល់។',
        'body_en' => 'Hi {name}, your order <strong>#{order}</strong> has been dispatched. You can confirm delivery once it arrives.',
        'cta_km' => 'តាមដានការបញ្ជាទិញ',
        'cta_en' => 'Track order',
    ],
    'payout_sent' => [
        'label'   => 'Payout sent (vendor)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការទូទាត់ត្រូវបានផ្ញើ',
        'subject_en' => 'Your payout has been sent',
        'heading_km' => 'ការទូទាត់ត្រូវបានផ្ញើ',
        'heading_en' => 'Payout sent',
        'body_km' => 'ជម្រាបសួរ {name}, ការទូទាត់សម្រាប់ការបញ្ជាទិញ <strong>#{order}</strong> ត្រូវបានផ្ញើទៅគណនី ABA របស់អ្នក។',
        'body_en' => 'Hi {name}, your payout for order <strong>#{order}</strong> has been sent to your ABA account.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'delivery_confirmed' => [
        'label'   => 'Delivery confirmed (vendor)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការដឹកជញ្ជូនត្រូវបានបញ្ជាក់ — ការទូទាត់នឹងមកដល់',
        'subject_en' => 'Delivery confirmed — payout incoming',
        'heading_km' => 'ការដឹកជញ្ជូនត្រូវបានបញ្ជាក់',
        'heading_en' => 'Delivery confirmed',
        'body_km' => 'ជម្រាបសួរ {name}, អ្នកទិញបានបញ្ជាក់ការទទួលការបញ្ជាទិញ <strong>#{order}</strong>។ ទីផ្សារនឹងដំណើរការការទូទាត់របស់អ្នកក្នុងពេលឆាប់ៗ។',
        'body_en' => 'Hi {name}, the buyer has confirmed receipt of order <strong>#{order}</strong>. Teepsaa will process your payout shortly.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'low_stock' => [
        'label'   => 'Low stock alert (vendor)',
        'tokens'  => '{name}, {product}, {units}',
        'subject_km' => 'ការជូនដំណឹងស្តុកជិតអស់ — {product}',
        'subject_en' => 'Low stock alert — {product}',
        'heading_km' => 'ការជូនដំណឹងស្តុកជិតអស់',
        'heading_en' => 'Low stock alert',
        'body_km' => 'ជម្រាបសួរ {name}, <strong>{product}</strong> នៅសល់តែ <strong>{units} គ្រឿង</strong> ប៉ុណ្ណោះ។ សូមបំពេញស្តុកឆាប់ៗ ដើម្បីបន្តលក់។',
        'body_en' => 'Hi {name}, <strong>{product}</strong> has only <strong>{units} remaining</strong>. Restock soon to keep selling.',
        'cta_km' => 'ធ្វើបច្ចុប្បន្នភាពស្តុក',
        'cta_en' => 'Update stock',
    ],
    'abandoned_cart' => [
        'label'   => 'Abandoned cart (buyer)',
        'tokens'  => '{name}, {cart_list}',
        'subject_km' => 'រទេះ ទីផ្សារ របស់អ្នកកំពុងរង់ចាំ',
        'subject_en' => 'Your teepsaa cart is waiting',
        'heading_km' => 'អ្នកបានទុកអ្វីមួយក្នុងរទេះ',
        'heading_en' => 'You left something in your cart',
        'body_km' => 'ជម្រាបសួរ {name}, អ្នកមានទំនិញកំពុងរង់ចាំក្នុងរទេះ ទីផ្សារ របស់អ្នក៖{cart_list}រទេះរបស់អ្នកត្រូវបានរក្សាទុក — ត្រឡប់មកវិញនៅពេលអ្នកត្រៀមរួច។',
        'body_en' => 'Hi {name}, you have items waiting in your teepsaa cart. Your cart is saved — head back whenever you\'re ready.',
        'cta_km' => 'ទៅរទេះរបស់ខ្ញុំ',
        'cta_en' => 'Go to my cart',
    ],
    'review_reminder' => [
        'label'   => 'Review reminder (buyer)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'តើការបញ្ជាទិញ ទីផ្សារ របស់អ្នកដូចម្តេច?',
        'subject_en' => 'How was your teepsaa order?',
        'heading_km' => 'តើការបញ្ជាទិញរបស់អ្នកដូចម្តេចដែរ?',
        'heading_en' => 'How was your order?',
        'body_km' => 'ជម្រាបសួរ {name}, ការបញ្ជាទិញ ទីផ្សារ <strong>{order}</strong> របស់អ្នកត្រូវបានដឹកជញ្ជូន។ យើងចង់ដឹងពីគំនិតរបស់អ្នក — វាចំណាយពេលតែបន្តិចប៉ុណ្ណោះ។',
        'body_en' => 'Hi {name}, your teepsaa order <strong>{order}</strong> was delivered. We\'d love to hear what you think — it only takes a moment.',
        'cta_km' => 'ទុកមតិយោបល់',
        'cta_en' => 'Leave a review',
    ],
    'verify_code' => [
        'label'   => 'Email verification code',
        'tokens'  => '{name}, {code}',
        'subject_km' => 'កូដផ្ទៀងផ្ទាត់ ទីផ្សារ របស់អ្នក',
        'subject_en' => 'Your Teepsaa verification code',
        'heading_km' => 'ផ្ទៀងផ្ទាត់អ៊ីមែលរបស់អ្នក',
        'heading_en' => 'Verify your email',
        'body_km' => 'ជម្រាបសួរ {name}, កូដផ្ទៀងផ្ទាត់របស់អ្នកគឺ៖{code}កូដនេះនឹងផុតកំណត់ក្នុងរយៈពេល ១៥ នាទី។ ប្រសិនបើអ្នកមិនបានបង្កើតគណនី ទីផ្សារ សូមមិនអើពើនឹងអ៊ីមែលនេះ។',
        'body_en' => 'Hi {name}, your verification code is shown above. It expires in 15 minutes. If you didn\'t create a Teepsaa account, ignore this email.',
        'cta_km' => null,
        'cta_en' => null,
    ],
    'reset_password' => [
        'label'   => 'Password reset',
        'tokens'  => '{name}, {link}',
        'subject_km' => 'កំណត់ពាក្យសម្ងាត់ ទីផ្សារ របស់អ្នកឡើងវិញ',
        'subject_en' => 'Reset your Teepsaa password',
        'heading_km' => 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
        'heading_en' => 'Reset your password',
        'body_km' => 'ជម្រាបសួរ {name}, សូមចុចលើតំណខាងក្រោមដើម្បីកំណត់ពាក្យសម្ងាត់របស់អ្នកឡើងវិញ។ តំណនេះមានសុពលភាពរយៈពេល ១ ម៉ោង។{link}ប្រសិនបើអ្នកមិនបានស្នើសុំកំណត់ពាក្យសម្ងាត់ឡើងវិញ សូមមិនអើពើនឹងអ៊ីមែលនេះ។',
        'body_en' => 'Hi {name}, click the link above to reset your password. This link is valid for 1 hour. If you didn\'t request a password reset, you can ignore this email.',
        'cta_km' => null,
        'cta_en' => null,
    ],
    'welcome_buyer' => [
        'label'   => 'Welcome (buyer)',
        'tokens'  => '{name}',
        'subject_km' => 'សូមស្វាគមន៍មកកាន់ ទីផ្សារ!',
        'subject_en' => 'Welcome to teepsaa!',
        'heading_km' => 'សូមស្វាគមន៍មកកាន់ ទីផ្សារ!',
        'heading_en' => 'Welcome to teepsaa!',
        'body_km' => 'ជម្រាបសួរ {name}, គណនីរបស់អ្នកត្រូវបានផ្ទៀងផ្ទាត់រួចរាល់។ ស្វែងរកហាង និងផលិតផលនៅទូទាំងទីក្រុងភ្នំពេញឥឡូវនេះ!',
        'body_en' => 'Hi {name}, your account is verified and ready. Start exploring stores and products across Phnom Penh!',
        'cta_km' => 'ចាប់ផ្តើមទិញទំនិញ',
        'cta_en' => 'Start shopping',
    ],
    'welcome_vendor' => [
        'label'   => 'Welcome (vendor)',
        'tokens'  => '{name}',
        'subject_km' => 'សូមស្វាគមន៍មកកាន់ ទីផ្សារ!',
        'subject_en' => 'Welcome to teepsaa!',
        'heading_km' => 'សូមស្វាគមន៍មកកាន់ ទីផ្សារ!',
        'heading_en' => 'Welcome to teepsaa!',
        'body_km' => 'ជម្រាបសួរ {name}, គណនីអ្នកលក់របស់អ្នកត្រូវបានផ្ទៀងផ្ទាត់រួចរាល់។ ជំហានបន្ទាប់៖ ដាក់ស្នើអាជីវកម្មរបស់អ្នក ដើម្បីចាប់ផ្តើមលក់នៅលើ ទីផ្សារ។',
        'body_en' => 'Hi {name}, your vendor account is verified. Next step: submit your business to start selling on teepsaa.',
        'cta_km' => 'ដាក់ស្នើអាជីវកម្ម',
        'cta_en' => 'Submit your business',
    ],
    'order_cancelled' => [
        'label'   => 'Order cancelled (buyer)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការបញ្ជាទិញ #{order} ត្រូវបានបោះបង់',
        'subject_en' => 'Order #{order} has been cancelled',
        'heading_km' => 'ការបញ្ជាទិញត្រូវបានបោះបង់',
        'heading_en' => 'Order cancelled',
        'body_km' => 'ជម្រាបសួរ {name}, ការបញ្ជាទិញ <strong>#{order}</strong> របស់អ្នកត្រូវបានបោះបង់។ ប្រសិនបើអ្នកបានបង់ប្រាក់រួចហើយ ប្រាក់នឹងត្រូវបង្វិលជូនតាម ABA។ មានសំណួរ? សូមទាក់ទងផ្នែកជំនួយ។',
        'body_en' => 'Hi {name}, your order <strong>#{order}</strong> has been cancelled. If you already paid, your payment will be refunded via ABA. Contact support if you have questions.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'refund_approved' => [
        'label'   => 'Return approved (buyer)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការស្នើសុំបង្វិលប្រាក់ត្រូវបានយល់ព្រម',
        'subject_en' => 'Your return has been approved',
        'heading_km' => 'ការស្នើសុំបង្វិលប្រាក់ត្រូវបានយល់ព្រម',
        'heading_en' => 'Return approved',
        'body_km' => 'ជម្រាបសួរ {name}, ការស្នើសុំបង្វិលប្រាក់សម្រាប់ការបញ្ជាទិញ <strong>#{order}</strong> ត្រូវបានយល់ព្រម។ សូមផ្ញើទំនិញត្រឡប់ទៅអ្នកលក់វិញ រួចបញ្ជាក់ការផ្ញើនៅក្នុងទំព័រការបញ្ជាទិញរបស់អ្នក។',
        'body_en' => 'Hi {name}, your refund request for order <strong>#{order}</strong> has been approved. Please send the item back to the vendor, then mark it as dispatched on your order page.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'refund_rejected' => [
        'label'   => 'Refund rejected (buyer)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការស្នើសុំបង្វិលប្រាក់ត្រូវបានបដិសេធ',
        'subject_en' => 'Your refund request was declined',
        'heading_km' => 'ការស្នើសុំបង្វិលប្រាក់ត្រូវបានបដិសេធ',
        'heading_en' => 'Refund request declined',
        'body_km' => 'ជម្រាបសួរ {name}, ការស្នើសុំបង្វិលប្រាក់សម្រាប់ការបញ្ជាទិញ <strong>#{order}</strong> ត្រូវបានបដិសេធ។ ប្រសិនបើអ្នកគិតថានេះជាកំហុស សូមទាក់ទងផ្នែកជំនួយ។',
        'body_en' => 'Hi {name}, your refund request for order <strong>#{order}</strong> was declined. If you believe this is a mistake, please contact support.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'refund_sent' => [
        'label'   => 'Refund sent (buyer)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ប្រាក់បង្វិលរបស់អ្នកត្រូវបានផ្ញើ',
        'subject_en' => 'Your refund has been sent',
        'heading_km' => 'ប្រាក់បង្វិលត្រូវបានផ្ញើ',
        'heading_en' => 'Refund sent',
        'body_km' => 'ជម្រាបសួរ {name}, ប្រាក់បង្វិលសម្រាប់ការបញ្ជាទិញ <strong>#{order}</strong> ត្រូវបានផ្ញើទៅគណនី ABA របស់អ្នក។',
        'body_en' => 'Hi {name}, your refund for order <strong>#{order}</strong> has been sent to your ABA account.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'refund_requested' => [
        'label'   => 'Refund requested (vendor)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការស្នើសុំបង្វិលប្រាក់ — ការបញ្ជាទិញ #{order}',
        'subject_en' => 'Refund requested — order #{order}',
        'heading_km' => 'ការស្នើសុំបង្វិលប្រាក់ថ្មី',
        'heading_en' => 'Refund requested',
        'body_km' => 'ជម្រាបសួរ {name}, អ្នកទិញបានស្នើសុំបង្វិលប្រាក់សម្រាប់ការបញ្ជាទិញ <strong>#{order}</strong>។ ទីផ្សារ នឹងពិនិត្យសំណើនេះ។ អ្នកអាចមើលព័ត៌មានលម្អិតក្នុងការបញ្ជាទិញរបស់អ្នក។',
        'body_en' => 'Hi {name}, the buyer has requested a refund for order <strong>#{order}</strong>. Teepsaa will review the request; you can see the details in your orders.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'vendor_new_order' => [
        'label'   => 'New order (vendor)',
        'tokens'  => '{name}, {order}',
        'subject_km' => 'ការបញ្ជាទិញថ្មី! #{order}',
        'subject_en' => 'New order! #{order}',
        'heading_km' => 'អ្នកមានការបញ្ជាទិញថ្មី!',
        'heading_en' => 'You have a new order!',
        'body_km' => 'ជម្រាបសួរ {name}, អ្នកមានការបញ្ជាទិញថ្មីដែលបានបង់ប្រាក់រួច <strong>#{order}</strong>។ សូមរៀបចំទំនិញ ហើយបញ្ជាក់ការបញ្ជូននៅពេលផ្ញើចេញ។',
        'body_en' => 'Hi {name}, you have a new paid order <strong>#{order}</strong>. Please prepare it and mark it dispatched when it ships.',
        'cta_km' => 'មើលការបញ្ជាទិញ',
        'cta_en' => 'View order',
    ],
    'business_submitted' => [
        'label'   => 'Business submitted (vendor)',
        'tokens'  => '{name}, {business}',
        'subject_km' => 'អាជីវកម្មរបស់អ្នកកំពុងត្រូវបានពិនិត្យ',
        'subject_en' => 'Your business is under review',
        'heading_km' => 'យើងបានទទួលការដាក់ស្នើរបស់អ្នក',
        'heading_en' => 'We received your submission',
        'body_km' => 'ជម្រាបសួរ {name}, យើងបានទទួលការដាក់ស្នើសម្រាប់ <strong>{business}</strong>។ យើងនឹងពិនិត្យ ហើយផ្ញើអ៊ីមែលជូនអ្នកនៅពេលយល់ព្រម។',
        'body_en' => 'Hi {name}, we received your submission for <strong>{business}</strong>. We\'ll review it and email you once it\'s approved.',
        'cta_km' => 'ទៅផ្ទាំងគ្រប់គ្រង',
        'cta_en' => 'Go to dashboard',
    ],
    'business_approved' => [
        'label'   => 'Business approved (vendor)',
        'tokens'  => '{name}, {business}',
        'subject_km' => 'អបអរសាទរ — ហាងរបស់អ្នកដំណើរការហើយ!',
        'subject_en' => 'Congratulations — your store is live!',
        'heading_km' => 'ហាងរបស់អ្នកដំណើរការហើយ!',
        'heading_en' => 'Your store is live!',
        'body_km' => 'ជម្រាបសួរ {name}, <strong>{business}</strong> ត្រូវបានយល់ព្រម ហើយឥឡូវនេះដំណើរការនៅលើ ទីផ្សារ។ បន្ថែមផលិតផលដើម្បីចាប់ផ្តើមលក់!',
        'body_en' => 'Hi {name}, <strong>{business}</strong> has been approved and is now live on teepsaa. Add products to start selling!',
        'cta_km' => 'បន្ថែមផលិតផល',
        'cta_en' => 'Add products',
    ],
    'business_rejected' => [
        'label'   => 'Business rejected (vendor)',
        'tokens'  => '{name}, {business}, {reason_km}, {reason_en}',
        'subject_km' => 'អំពីការដាក់ស្នើអាជីវកម្មរបស់អ្នក',
        'subject_en' => 'About your business submission',
        'heading_km' => 'ការដាក់ស្នើមិនត្រូវបានយល់ព្រម',
        'heading_en' => 'Submission not approved',
        'body_km' => 'ជម្រាបសួរ {name}, ជាអកុសល <strong>{business}</strong> មិនត្រូវបានយល់ព្រមនៅពេលនេះទេ។ សូមពិនិត្យព័ត៌មានអាជីវកម្មរបស់អ្នកក្នុងការកំណត់ កែតម្រូវ រួចដាក់ស្នើឡើងវិញ។{reason_km}',
        'body_en' => 'Hi {name}, unfortunately <strong>{business}</strong> was not approved this time. Fix your business details in Settings, then resubmit it for review.{reason_en}',
        'cta_km' => 'ទៅការកំណត់',
        'cta_en' => 'Go to Settings',
    ],
    'business_deleted' => [
        'label'   => 'Business deleted (vendor)',
        'tokens'  => '{name}, {business}',
        'subject_km' => 'អាជីវកម្មរបស់អ្នកត្រូវបានលុប',
        'subject_en' => 'Your business has been deleted',
        'heading_km' => 'អាជីវកម្មត្រូវបានលុប',
        'heading_en' => 'Business deleted',
        'body_km' => 'ជម្រាបសួរ {name}, <strong>{business}</strong> ត្រូវបានលុបចេញពី ទីផ្សារ។ ប្រសិនបើអ្នកមិនបានស្នើសុំការលុបនេះទេ សូមទាក់ទងផ្នែកជំនួយភ្លាមៗ។ អ្នកអាចបង្កើតអាជីវកម្មថ្មីបានគ្រប់ពេល។',
        'body_en' => 'Hi {name}, <strong>{business}</strong> has been removed from teepsaa. If you didn\'t request this, contact support immediately. You can set up a new business anytime.',
        'cta_km' => null,
        'cta_en' => null,
    ],
    'password_changed' => [
        'label'   => 'Password changed (security notice)',
        'tokens'  => '{name}',
        'subject_km' => 'ពាក្យសម្ងាត់របស់អ្នកត្រូវបានផ្លាស់ប្តូរ',
        'subject_en' => 'Your password was changed',
        'heading_km' => 'ពាក្យសម្ងាត់ត្រូវបានផ្លាស់ប្តូរ',
        'heading_en' => 'Password changed',
        'body_km' => 'ជម្រាបសួរ {name}, ពាក្យសម្ងាត់គណនី ទីផ្សារ របស់អ្នកទើបតែត្រូវបានផ្លាស់ប្តូរ។ ប្រសិនបើមិនមែនអ្នកទេ សូមកំណត់ពាក្យសម្ងាត់ឡើងវិញភ្លាមៗ ហើយទាក់ទងផ្នែកជំនួយ។',
        'body_en' => 'Hi {name}, the password for your teepsaa account was just changed. If this wasn\'t you, reset your password immediately and contact support.',
        'cta_km' => null,
        'cta_en' => null,
    ],
    'account_deleted' => [
        'label'   => 'Account deleted (confirmation)',
        'tokens'  => '{name}',
        'subject_km' => 'គណនីរបស់អ្នកត្រូវបានលុប',
        'subject_en' => 'Your account has been deleted',
        'heading_km' => 'គណនីត្រូវបានលុប',
        'heading_en' => 'Account deleted',
        'body_km' => 'ជម្រាបសួរ {name}, គណនី ទីផ្សារ របស់អ្នកត្រូវបានលុប។ យើងសោកស្តាយដែលឃើញអ្នកចាកចេញ — សូមស្វាគមន៍ត្រឡប់មកវិញគ្រប់ពេល។ ប្រសិនបើអ្នកមិនបានស្នើសុំការលុបនេះទេ សូមទាក់ទងផ្នែកជំនួយភ្លាមៗ។',
        'body_en' => 'Hi {name}, your teepsaa account has been deleted. We\'re sorry to see you go — you\'re welcome back anytime. If you didn\'t request this, contact support immediately.',
        'cta_km' => null,
        'cta_en' => null,
    ],
    // {reason} is the text the admin typed on the suspend form — it is shown
    // to the user, so keep it written for their eyes.
    'buyer_suspended' => [
        'label'   => 'Account suspended (buyer)',
        'tokens'  => '{name}, {reason}',
        'subject_km' => 'គណនីរបស់អ្នកត្រូវបានផ្អាក',
        'subject_en' => 'Your account has been suspended',
        'heading_km' => 'គណនីត្រូវបានផ្អាក',
        'heading_en' => 'Account suspended',
        'body_km' => 'ជម្រាបសួរ {name}, គណនី ទីផ្សារ របស់អ្នកត្រូវបានផ្អាក ហើយអ្នកមិនអាចចូលប្រើបានទេនៅពេលនេះ។<br><br><strong>មូលហេតុ៖</strong> {reason}<br><br>ប្រសិនបើអ្នកគិតថានេះជាកំហុស សូមទាក់ទងផ្នែកជំនួយ ហើយយើងនឹងពិនិត្យឡើងវិញ។',
        'body_en' => 'Hi {name}, your teepsaa account has been suspended and you will not be able to sign in for now.<br><br><strong>Reason:</strong> {reason}<br><br>If you believe this is a mistake, contact support and we will review it.',
        'cta_km' => 'ទាក់ទងផ្នែកជំនួយ',
        'cta_en' => 'Contact support',
    ],
    'buyer_reinstated' => [
        'label'   => 'Suspension lifted (buyer)',
        'tokens'  => '{name}',
        'subject_km' => 'គណនីរបស់អ្នកបានដំណើរការឡើងវិញ',
        'subject_en' => 'Your account has been restored',
        'heading_km' => 'ការផ្អាកត្រូវបានដកចេញ',
        'heading_en' => 'Suspension lifted',
        'body_km' => 'ជម្រាបសួរ {name}, ការផ្អាកលើគណនី ទីផ្សារ របស់អ្នកត្រូវបានដកចេញ។ ឥឡូវអ្នកអាចចូលប្រើ និងទិញទំនិញបានធម្មតាវិញហើយ។ សូមអរគុណសម្រាប់ការអត់ធ្មត់។',
        'body_en' => 'Hi {name}, the suspension on your teepsaa account has been lifted. You can sign in and shop as normal again. Thanks for your patience.',
        'cta_km' => 'ចូលគណនី',
        'cta_en' => 'Sign in',
    ],
    'vendor_suspended' => [
        'label'   => 'Account suspended (vendor)',
        'tokens'  => '{name}, {reason}',
        'subject_km' => 'គណនីអ្នកលក់របស់អ្នកត្រូវបានផ្អាក',
        'subject_en' => 'Your vendor account has been suspended',
        'heading_km' => 'គណនីអ្នកលក់ត្រូវបានផ្អាក',
        'heading_en' => 'Vendor account suspended',
        'body_km' => 'ជម្រាបសួរ {name}, គណនីអ្នកលក់របស់អ្នកត្រូវបានផ្អាក។ អ្នកមិនអាចចូលប្រើបានទេ ហើយហាងរបស់អ្នកមិនបង្ហាញដល់អ្នកទិញនៅពេលនេះទេ។<br><br><strong>មូលហេតុ៖</strong> {reason}<br><br>ការបញ្ជាទិញ និងកំណត់ត្រាទូទាត់របស់អ្នកនៅតែរក្សាទុក។ ប្រសិនបើអ្នកគិតថានេះជាកំហុស សូមទាក់ទងផ្នែកជំនួយ ហើយយើងនឹងពិនិត្យឡើងវិញ។',
        'body_en' => 'Hi {name}, your vendor account has been suspended. You cannot sign in, and your storefront is not visible to buyers for now.<br><br><strong>Reason:</strong> {reason}<br><br>Your orders and payout records are kept. If you believe this is a mistake, contact support and we will review it.',
        'cta_km' => 'ទាក់ទងផ្នែកជំនួយ',
        'cta_en' => 'Contact support',
    ],
    'vendor_reinstated' => [
        'label'   => 'Suspension lifted (vendor)',
        'tokens'  => '{name}',
        'subject_km' => 'គណនីអ្នកលក់របស់អ្នកបានដំណើរការឡើងវិញ',
        'subject_en' => 'Your vendor account has been restored',
        'heading_km' => 'ការផ្អាកត្រូវបានដកចេញ',
        'heading_en' => 'Suspension lifted',
        'body_km' => 'ជម្រាបសួរ {name}, ការផ្អាកលើគណនីអ្នកលក់របស់អ្នកត្រូវបានដកចេញ។ ឥឡូវអ្នកអាចចូលប្រើឡើងវិញ ហើយហាងរបស់អ្នកបង្ហាញដល់អ្នកទិញវិញហើយ។ សូមអរគុណសម្រាប់ការអត់ធ្មត់។',
        'body_en' => 'Hi {name}, the suspension on your vendor account has been lifted. You can sign in again and your storefront is visible to buyers. Thanks for your patience.',
        'cta_km' => 'ចូលគណនី',
        'cta_en' => 'Sign in',
    ],
    // Security notice, not a courtesy one: this is how a vendor finds out that
    // somebody changed where their money goes. It must go out on every change,
    // including changes the vendor made themselves.
    'vendor_bank_changed' => [
        'label'   => 'Bank details changed (vendor)',
        'tokens'  => '{name}, {account_name}, {changed_at}',
        'subject_km' => 'ព័ត៌មានធនាគាររបស់អ្នកត្រូវបានផ្លាស់ប្តូរ',
        'subject_en' => 'Your payout bank details were changed',
        'heading_km' => 'ព័ត៌មានធនាគារត្រូវបានផ្លាស់ប្តូរ',
        'heading_en' => 'Payout bank details changed',
        'body_km' => 'ជម្រាបសួរ {name}, ព័ត៌មានធនាគារ ABA សម្រាប់ការទូទាត់របស់អ្នកត្រូវបានផ្លាស់ប្តូរនៅ {changed_at}។<br><br><strong>ឈ្មោះគណនីថ្មី៖</strong> {account_name}<br><br>ការទូទាត់ទាំងអស់ត្រូវបានផ្អាករយៈពេល ២៤ ម៉ោង។ <strong>ប្រសិនបើអ្នកមិនបានធ្វើការផ្លាស់ប្តូរនេះទេ សូមទាក់ទងផ្នែកជំនួយភ្លាមៗ</strong> — មានគេអាចចូលប្រើគណនីរបស់អ្នក។',
        'body_en' => 'Hi {name}, the ABA bank details we use to pay you were changed on {changed_at}.<br><br><strong>New account name:</strong> {account_name}<br><br>Payouts to you are on hold for 24 hours. <strong>If you did not make this change, contact support immediately</strong> — someone else may have access to your account.',
        'cta_km' => 'ទាក់ទងផ្នែកជំនួយ',
        'cta_en' => 'Contact support',
    ],
];
