<?php
// Source: Wikipedia individual Khan articles (verified May 2026)
// 14 Khans, 105 Sangkats total — matches Phnom Penh#Administration
// Note: Boeng Keng Kang became its own Khan on Jan 8 2019 (split from Chamkar Mon)
// Note: Prampir Makara is the official name for what was formerly "7 Makara"
return [
    'Chamkar Mon' => [
        'Boeng Trabaek',
        'Phsar Daeum Thkov',
        'Tonle Basak',
        'Tuol Tumpung I',
        'Tuol Tumpung II',
    ],
    'Doun Penh' => [
        'Boeng Reang',
        'Chaktomuk',
        'Chey Chumneas',
        'Phsar Chas',
        'Phsar Kandal I',
        'Phsar Kandal II',
        'Phsar Thmey I',
        'Phsar Thmey II',
        'Phsar Thmey III',
        'Srah Chak',
        'Wat Phnom',
    ],
    'Prampir Makara' => [
        'Boeng Prolit',
        'Mittapheap',
        'Monorom',
        'Orussey I',
        'Orussey II',
        'Orussey III',
        'Orussey IV',
        'Veal Vong',
    ],
    'Tuol Kouk' => [
        'Boeng Kak I',
        'Boeng Kak II',
        'Boeng Salang',
        'Phsar Daeumkor',
        'Phsar Depo I',
        'Phsar Depo II',
        'Phsar Depo III',
        'Tuek L\'ak I',
        'Tuek L\'ak II',
        'Tuek L\'ak III',
    ],
    'Boeng Keng Kang' => [
        'Boeng Keng Kang I',
        'Boeng Keng Kang II',
        'Boeng Keng Kang III',
        'Olympic',
        'Tumnob Tuek',
        'Tuol Svay Prey I',
        'Tuol Svay Prey II',
    ],
    'Mean Chey' => [
        'Boeng Tumpun I',
        'Boeng Tumpun II',
        'Chak Angrae Kraom',
        'Chak Angrae Leu',
        'Stueng Mean Chey I',
        'Stueng Mean Chey II',
        'Stueng Mean Chey III',
    ],
    'Chbar Ampov' => [
        'Chbar Ampov I',
        'Chbar Ampov II',
        'Kbal Koh',
        'Nirouth',
        'Prek Aeng',
        'Prek Pra',
        'Prek Thmei',
        'Veal Sbov',
    ],
    'Russey Keo' => [
        'Chrang Chamreh I',
        'Chrang Chamreh II',
        'Kilomet Prammouy',
        'Russey Keo',
        'Svay Pak',
        'Tuol Sangkae I',
        'Tuol Sangkae II',
    ],
    'Sen Sok' => [
        'Khmuonh',
        'Kouk Khleang',
        'Krang Thnong',
        'Ou Baek K\'am',
        'Phnom Penh Thmei',
        'Tuek Thla',
    ],
    'Pou Senchey' => [
        'Chaom Chau I',
        'Chaom Chau II',
        'Chaom Chau III',
        'Kakab I',
        'Kakab II',
        'Samraong Kraom',
        'Trapeang Krasang',
    ],
    'Chroy Changvar' => [
        'Bak Khaeng',
        'Chroy Changvar',
        'Koh Dach',
        'Prek Leap',
        'Prek Ta Sek',
    ],
    'Dangkao' => [
        'Cheung Aek',
        'Dangkao',
        'Kong Noy',
        'Krang Pongro',
        'Pong Tuek',
        'Preaek Kampues',
        'Prey Sa',
        'Prey Veaeng',
        'Roluos',
        'Sak Sampov',
        'Spean Thma',
        'Tien',
    ],
    'Prek Pnov' => [
        'Kouk Roka',
        'Ponhea Pon',
        'Ponsang',
        'Prek Pnov',
        'Samraong',
    ],
    'Kamboul' => [
        'Boeng Thum',
        'Kamboul',
        'Kantouk',
        'Ovlaok',
        'Phleung Chheh Roteh',
        'Prateah Lang',
        'Snaor',
    ],
];
